services:
  - type: web
    name: serena
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: SERENA
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: API_URL
        value: https://api.arcmusic.fun
      - key: API_KEY
        sync: false
      - key: API_KEYS
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: serena
      - key: OWNER_ID
        sync: false
      - key: SUDO_USERS
        sync: false
      - key: UPDATES_CHANNEL_URL
        value: https://t.me/serenaunzipbot
      - key: WEBHOOK_PATH
        value: /telegram/webhook
      - key: WEBHOOK_SECRET
        sync: false
